import { SALE_DEFAULTS, Sale } from '@core/models';

/** Fixed bill shown in the receipt preview of the store-info form. */
export const SAMPLE_SALE: Sale = {
  ...SALE_DEFAULTS,
  id: 0,
  orderNo: 'POS-20261004-0001',
  date: new Date(2026, 9, 4, 14, 5).toISOString(),
  cashier: 'Admin',
  customer: '',
  lines: [
    {
      productId: 1,
      sku: 'NB-001',
      name: 'โน้ตบุ๊ก 14 นิ้ว',
      shortName: 'NB Lenovo Slim5 14"',
      unit: 'เครื่อง',
      factor: 1,
      qty: 1,
      unitPrice: 24900,
      itemDiscount: 0,
      billDiscount: 300,
      amount: 24600,
      vatType: 'vat7',
      vat: 1609.35,
      promotionIds: [3],
      freeOfPromotionId: null,
      serial: 'NB-100000001',
      warrantyMonths: 24,
      cogs: 0,
    },
    {
      productId: 2,
      sku: 'MS-010',
      name: 'เมาส์ไร้สาย',
      shortName: 'เมาส์ไร้สาย M240',
      unit: 'ชิ้น',
      factor: 1,
      qty: 1,
      unitPrice: 0,
      itemDiscount: 0,
      billDiscount: 0,
      amount: 0,
      vatType: 'vat7',
      vat: 0,
      promotionIds: [3],
      freeOfPromotionId: 3,
      serial: null,
      warrantyMonths: 12,
      cogs: 0,
    },
  ],
  payments: [
    {
      methodId: 1,
      name: 'เงินสด',
      type: 'cash',
      amount: 24600,
      tendered: 25000,
      reference: '',
      installmentMonths: null,
    },
  ],
  subtotal: 24900,
  billDiscount: 300,
  total: 24600,
  vat: 1609.35,
  change: 400,
  billPromotionIds: [2],
  itemCount: 2,
  status: 'paid',
};
